version: '3.3'

services:
  database:
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: test
      MYSQL_PASS: pass
      MYSQL_ROOT_PASSWORD: 12345

